import { sidebar } from 'vuepress-theme-hope';

export const zh = sidebar({
  '/about': [''],
  '/composition/': [''],
  '/operating-system/': ['', 'windows', 'ubuntu', 'arch'],
  '/compiler/': [''],
  '/network/': [''],
  '/ai/': ['', 'dl'],
  '/c/': [
    '',
    'syntax',
    'function',
    'array',
    'pointer',
    'struct-union',
    'preprocessing',
    'storage',
    'malloc',
    'standard',
    'input-memory-buffer',
  ],
  '/java/': [
    '',
    'syntax',
    'class',
    'string',
    'ds',
    'interface',
    'generics',
    'error',
    'standard',
    'multithreading',
  ],
  '/js/': [
    '',
    'syntax',
    'function',
    'object',
    'string',
    'data-structure',
    'destructuring-assignment',
    'prototype',
    'class',
    'error',
    'promise-async-await',
    'proxy-reflect',
    'module',
    'event-loop',
    'standard',
    'quality',
    'typescript',
    'node',
  ],
  '/python/': [
    '',
    'syntax',
    'ds',
    'function',
    'class',
    'module',
    'comprehensions',
    'exception',
    'standard',
    'spider',
  ],
  '/rust/': [
    '',
    'syntax',
    'function',
    'data-structure',
    'struct',
    'enum',
    'generic',
    'trait',
    'closure',
    'iterator',
    'error',
    'smart-pointer',
    'concurrent',
    'macro',
    'cargo',
    'owner-borrowing-lifecycle',
    'standard',
    'libraries',
  ],
  '/ds-algorithm/': [
    '',
    'array',
    'linkedlist',
    'stack',
    'queue',
    'string',
    'tree',
    'graph',
    'other',
    'recursion',
    'find',
    'sort',
    'random',
    'think',
  ],
  '/database/': ['', 'sql', 'nosql'],
  '/html-css/': [
    '',
    'elements',
    'selectors',
    'box-model',
    'css',
    'layout',
    'value',
    'responsive-design',
    'better-code',
    'trick',
  ],
  '/webapi/': [
    '',
    'browser',
    'dom',
    'event',
    'network',
    'storage',
    'drag',
    'binary',
    'canvas',
    'worker',
    'webrtc',
    'wasm',
    'browser_extends',
  ],
  '/framework/': [
    'vue',
    'react',
    'express',
    'koa',
    'reactnative',
    'electron',
    'tauri',
  ],
  '/subject/': [
    'english',
    'nce',
    'math',
    'physics',
    'chemistry',
    'biology',
    'history',
    'logic',
    'economics-finance',
    'interdisciplinarity',
  ],
  '/sundry/': [
    '',
    'tools',
    'problems',
    'unplaced',
    'skill',
    'git',
    'adb',
    'http',
    'latex',
    'learntolearn',
    'nginx',
    'frontend',
    'regex',
    'interview',
    'openssl',
    'game-sport',
    'cicd',
    'security',
    'software-design',
    'ui',
    'packet-capture',
    'crypto',
    'miniprogram',
    'harmonica',
    'libraries',
    'silkworm',
    'ai-products',
  ],
});
